import { DISCOVER_1, DISCOVER_2, DISCOVER_3, DISCOVER_CMPNY, SRC_COMPANY } from 'assets/images';

export const DiscoverData = [
	{
		img: DISCOVER_CMPNY,
		companyName: 'Oracle',
		data: [
			{
				img: DISCOVER_1,
				title: 'Navigating the next wave of private equity 1',
				desc: `Winna Brown, Private Equity (PE) Leader in the EY Americas Financial Accounting Advisory Services practice, joins podcast host Myles Corson to discuss PE',1,dp,p`,
				srcIcon: SRC_COMPANY,
				srcName: 'Mint',
				date: '27 Dec 2019',
			},
			{
				img: DISCOVER_2,
				title: 'Navigating the next wave of private equity 2',
				desc: `Winna Brown, Private Equity (PE) Leader in the EY Americas Financial Accounting Advisory Services practice, joins podcast host Myles Corson to discuss PE',1,dp,p`,
				srcIcon: SRC_COMPANY,
				srcName: 'Mint',
				date: '27 Dec 2019',
			},
			{
				img: DISCOVER_3,
				title: 'Navigating the next wave of private equity 3',
				desc: `Winna Brown, Private Equity (PE) Leader in the EY Americas Financial Accounting Advisory Services practice, joins podcast host Myles Corson to discuss PE',1,dp,p`,
				srcIcon: SRC_COMPANY,
				srcName: 'Mint',
				date: '27 Dec 2019',
			},
			{
				img: DISCOVER_1,
				title: 'Navigating the next wave of private equity 4',
				desc: `Winna Brown, Private Equity (PE) Leader in the EY Americas Financial Accounting Advisory Services practice, joins podcast host Myles Corson to discuss PE',1,dp,p`,
				srcIcon: SRC_COMPANY,
				srcName: 'Mint',
				date: '27 Dec 2019',
			},
		],
	},
	{
		img: DISCOVER_CMPNY,
		companyName: 'Oracle 1',
		data: [
			{
				img: DISCOVER_1,
				title: 'Navigating the next wave of private equity 11',
				desc: `Winna Brown, Private Equity (PE) Leader in the EY Americas Financial Accounting Advisory Services practice, joins podcast host Myles Corson to discuss PE',1,dp,p`,
				srcIcon: SRC_COMPANY,
				srcName: 'Mint',
				date: '27 Dec 2019',
			},
			{
				img: DISCOVER_2,
				title: 'Navigating the next wave of private equity 22',
				desc: `Winna Brown, Private Equity (PE) Leader in the EY Americas Financial Accounting Advisory Services practice, joins podcast host Myles Corson to discuss PE',1,dp,p`,
				srcIcon: SRC_COMPANY,
				srcName: 'Mint',
				date: '27 Dec 2019',
			},
			{
				img: DISCOVER_3,
				title: 'Navigating the next wave of private equity 33',
				desc: `Winna Brown, Private Equity (PE) Leader in the EY Americas Financial Accounting Advisory Services practice, joins podcast host Myles Corson to discuss PE',1,dp,p`,
				srcIcon: SRC_COMPANY,
				srcName: 'Mint',
				date: '27 Dec 2019',
			},
			{
				img: DISCOVER_1,
				title: 'Navigating the next wave of private equity 44',
				desc: `Winna Brown, Private Equity (PE) Leader in the EY Americas Financial Accounting Advisory Services practice, joins podcast host Myles Corson to discuss PE',1,dp,p`,
				srcIcon: SRC_COMPANY,
				srcName: 'Mint',
				date: '27 Dec 2019',
			},
		],
	},
	{
		img: DISCOVER_CMPNY,
		companyName: 'Oracle 2',
		data: [
			{
				img: DISCOVER_1,
				title: 'Navigating the next wave of private equity 55',
				desc: `Winna Brown, Private Equity (PE) Leader in the EY Americas Financial Accounting Advisory Services practice, joins podcast host Myles Corson to discuss PE',1,dp,p`,
				srcIcon: SRC_COMPANY,
				srcName: 'Mint',
				date: '27 Dec 2019',
			},
			{
				img: DISCOVER_2,
				title: 'Navigating the next wave of private equity 66',
				desc: `Winna Brown, Private Equity (PE) Leader in the EY Americas Financial Accounting Advisory Services practice, joins podcast host Myles Corson to discuss PE',1,dp,p`,
				srcIcon: SRC_COMPANY,
				srcName: 'Mint',
				date: '27 Dec 2019',
			},
			{
				img: DISCOVER_3,
				title: 'Navigating the next wave of private equity 77',
				desc: `Winna Brown, Private Equity (PE) Leader in the EY Americas Financial Accounting Advisory Services practice, joins podcast host Myles Corson to discuss PE',1,dp,p`,
				srcIcon: SRC_COMPANY,
				srcName: 'Mint',
				date: '27 Dec 2019',
			},
			{
				img: DISCOVER_1,
				title: 'Navigating the next wave of private equity 88',
				desc: `Winna Brown, Private Equity (PE) Leader in the EY Americas Financial Accounting Advisory Services practice, joins podcast host Myles Corson to discuss PE',1,dp,p`,
				srcIcon: SRC_COMPANY,
				srcName: 'Mint',
				date: '27 Dec 2019',
			},
		],
	},
];
