import { JOBLOG } from 'assets/images';

export const jobData = [
	{
		id: 81,
		jobTitle: 'Risk Analytics Consultant',
		company: 'Wells Fargo',
		location: 'Bengaluru',
		experience: '4+ yrs',
		salary: 'High Salary',
		jobType: 'Full-time',
		workType: 'From Office',
		salaryType: 'High Salary',
		connections: 10,
		applyEarly: 'Apply Early',
		logo: JOBLOG,
		progressPercentage: 78,
		status: 'Great',
	},
	{
		id: 82,
		jobTitle: 'Software Engineer',
		company: 'Google',
		location: 'Mountain',
		experience: '3-5 yrs',
		salary: 'Not Disclosed',
		jobType: 'Full-time',
		workType: 'Hybrid',
		salaryType: 'High Salary',
		connections: 10,
		applyEarly: 'Apply Early',
		logo: JOBLOG,
		progressPercentage: 55,
		status: 'Average',
	},
	{
		id: 83,
		jobTitle: 'Data Scientist',
		company: 'Amazon',
		location: 'Seattle, WA',
		experience: '2-4 yrs',
		salary: 'Not Disclosed',
		jobType: 'Contract',
		workType: 'Remote',
		salaryType: 'High Salary',
		connections: 10,
		applyEarly: 'Apply Early',
		logo: JOBLOG,
		progressPercentage: 95,
		status: 'Great',
	},
	{
		id: 84,
		jobTitle: 'Data Scientist',
		company: 'Amazon',
		location: 'Seattle, WA',
		experience: '2-4 yrs',
		salary: 'Not Disclosed',
		jobType: 'Contract',
		workType: 'Remote',
		salaryType: 'High Salary',
		connections: 6,
		applyEarly: 'Apply Early',
		logo: JOBLOG,
		progressPercentage: 45,
		status: 'Poor',
	},
];
