export const statesData = [
	{
		value: 'IN',
		label: 'India',
		states: [
			'Andhra Pradesh',
			'Arunachal Pradesh',
			'Assam',
			'Bihar',
			'Chhattisgarh',
			'Goa',
			'Gujarat',
			'Haryana',
			'Himachal Pradesh',
			'Jharkhand',
			'Karnataka',
			'Kerala',
			'Madhya Pradesh',
			'Maharashtra',
			'Manipur',
			'Meghalaya',
			'Mizoram',
			'Nagaland',
			'Odisha',
			'Punjab',
		],
	},
	{
		value: 'US',
		label: 'United States',
		states: [
			'Alabama',
			'Alaska',
			'Arizona',
			'Arkansas',
			'California',
			'Colorado',
			'Connecticut',
			'Delaware',
			'Florida',
			'Georgia',
			'Hawaii',
			'Idaho',
			'Illinois',
			'Indiana',
			'Iowa',
			'Kansas',
			'Kentucky',
			'Louisiana',
			'Maine',
		],
	},
	{
		value: 'CA',
		label: 'Canada',
		states: [
			'Alberta',
			'British Columbia',
			'Manitoba',
			'New Brunswick',
			'Newfoundland and Labrador',
			'Nova Scotia',
			'Ontario',
			'Prince Edward Island',
			'Quebec',
			'Saskatchewan',
		],
	},
	{
		value: 'DE',
		label: 'Germany',
		states: [
			'Baden-Württemberg',
			'Bavaria',
			'Berlin',
			'Brandenburg',
			'Bremen',
			'Hamburg',
			'Hesse',
			'Lower Saxony',
			'Mecklenburg-Vorpommern',
			'North Rhine-Westphalia',
		],
	},
	{
		value: 'JP',
		label: 'Japan',
		states: [
			'Aichi',
			'Akita',
			'Aomori',
			'Chiba',
			'Ehime',
			'Fukui',
			'Fukuoka',
			'Fukushima',
			'Gifu',
			'Gunma',
		],
	},
	{
		value: 'AU',
		label: 'Australia',
		states: [
			'New South Wales',
			'Queensland',
			'South Australia',
			'Tasmania',
			'Victoria',
			'Western Australia',
			'Australian Capital Territory',
			'Northern Territory',
		],
	},
	{
		value: 'BR',
		label: 'Brazil',
		states: [
			'Acre',
			'Alagoas',
			'Amapá',
			'Amazonas',
			'Bahia',
			'Ceará',
			'Espírito Santo',
			'Goiás',
			'Maranhão',
			'Mato Grosso',
		],
	},
	{
		value: 'FR',
		label: 'France',
		states: [
			'Auvergne-Rhône-Alpes',
			'Bourgogne-Franche-Comté',
			'Brittany',
			'Centre-Val de Loire',
			'Corsica',
			'Grand Est',
			'Hauts-de-France',
			'Île-de-France',
			'Normandy',
			'Nouvelle-Aquitaine',
		],
	},
	{
		value: 'ZA',
		label: 'South Africa',
		states: [
			'Eastern Cape',
			'Free State',
			'Gauteng',
			'KwaZulu-Natal',
			'Limpopo',
			'Mpumalanga',
			'North West',
			'Northern Cape',
			'Western Cape',
		],
	},
	{
		value: 'CN',
		label: 'China',
		states: [
			'Anhui',
			'Beijing',
			'Chongqing',
			'Fujian',
			'Gansu',
			'Guangdong',
			'Guangxi',
			'Guizhou',
			'Hainan',
			'Hebei',
		],
	},
];
