import { PROFILE_PIC } from 'assets/images';

export const users = [
	{
		id: 201,
		name: 'Anne Doe',
		position: 'Junior Consultant',
		company: 'Timo Digital Bank',
		mutuals: 3,
		connections: 23,
		image: PROFILE_PIC,
	},
	{
		id: 202,
		name: 'Anne Doe',
		position: 'Junior Consultant',
		company: 'Timo Digital Bank',
		mutuals: 3,
		connections: 23,
		image: PROFILE_PIC,
	},
	{
		id: 203,
		name: 'Anne Doe',
		position: 'Junior Consultant',
		company: 'Timo Digital Bank',
		mutuals: 3,
		connections: 23,
		image: PROFILE_PIC,
	},
	{
		id: 204,
		name: 'Anne Doe',
		position: 'Junior Consultant',
		company: 'Timo Digital Bank',
		mutuals: 3,
		connections: 23,
		image: PROFILE_PIC,
	},
	{
		id: 205,
		name: 'Anne Doe',
		position: 'Junior Consultant',
		company: 'Timo Digital Bank',
		mutuals: 3,
		connections: 23,
		image: PROFILE_PIC,
	},
	{
		id: 206,
		name: 'Anne Doe',
		position: 'Junior Consultant',
		company: 'Timo Digital Bank',
		mutuals: 3,
		connections: 23,
		image: PROFILE_PIC,
	},
];
